### ISSUE TITLE
uplifting APIs to  be k8s 1.22.x compatible

### ISSUE THREAD

**Issue by kashifest** [jenting/kucero#23]
There are some APIs which are removed/deprecated in k8s 1.22.x.  When can we expect a release with the uplifted apis/modules?

**Comment by kashifest** [comment]
Atleast CSR needs to be uplifted to v1 [here](https://github.com/SUSE/kucero/blob/master/controllers/certificatesigningrequest_controller.go#L25) 
`"no matches for kind \"CertificateSigningRequest\" in version \"certificates.k8s.io/v1beta1\"`

**Comment by jenting** [comment]
Sure, let me check how to tackle different Kubernetes versions, stay tune.
