### ISSUE TITLE
Unsupported authorization API versions in kucero as per k8s 1.22 and approver adaptation issue

### ISSUE THREAD

**Issue by kashifest** [jenting/kucero#29]
We tested kucero 1.5.1 CSRs signing in a kubernetes 1.22 cluster and noticed the CSRs were not being approved.

Kucero logs pointed to issues with the SAR. e.g:

```
time="2021-11-08T09:13:56Z" level=info msg=Signing
time="2021-11-08T09:13:56Z" level=error msg="SubjectAccessReview failed: the server could not find the requested resource"

```
We noticed that the Authorization API used in Kucero, is also V1beta1 and has been [removed](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#subjectaccessreview-resources-v122) in Kubernetes 1.22.

`The authorization.k8s.io/v1beta1 API version of LocalSubjectAccessReview, SelfSubjectAccessReview, and SubjectAccessReview is no longer served as of v1.22.`

After changing the API to V1 and testing, the CSRs were issued but the state didn't got changed to approved. Checking the kubelet code because of this missing state, kubelet will not get the certificate.

We tried adding a condition in the approver part and that seems to work. Perhaps this was not needed in older versions.

The following changes lead to kucero working in k8s 1.22

```
diff --git a/controllers/certificatesigningrequest_controller.go b/controllers/certificatesigningrequest_controller.go
index 29144b4..c229d5d 100644
--- a/controllers/certificatesigningrequest_controller.go
+++ b/controllers/certificatesigningrequest_controller.go
@@ -21,7 +21,7 @@ import (
  "crypto/x509"
  "fmt"
- authorization "k8s.io/api/authorization/v1beta1"
+ authorization "k8s.io/api/authorization/v1"
  capi "k8s.io/api/certificates/v1"
  capiv1beta1 "k8s.io/api/certificates/v1beta1"
  corev1 "k8s.io/api/core/v1"
@@ -154,7 +154,7 @@ func (r *CertificateSigningRequestSigningReconciler) authorize(csr *capi.Certifi
      ResourceAttributes: &rattrs,
    },
  }
- sar, err := r.ClientSet.AuthorizationV1beta1().SubjectAccessReviews().Create(context.TODO(), sar, metav1.CreateOptions{})
+ sar, err := r.ClientSet.AuthorizationV1().SubjectAccessReviews().Create(context.TODO(), sar, metav1.CreateOptions{})
  if err != nil {
    return false, err
  }
@@ -165,6 +165,7 @@ func appendApprovalCondition(csr *capi.CertificateSigningRequest, message string
  csr.Status.Conditions = append(csr.Status.Conditions, capi.CertificateSigningRequestCondition{
    Type:    capi.CertificateApproved,
    Reason:  "AutoApproved by kucero",
+   Status:  corev1.ConditionTrue,
    Message: message,
  })
 }
```

**Comment by jenting** [comment]
Thank you. I'll take time to tackle it. And thanks for your approach on fix it.

**Comment by kashifest** [comment]
> Thank you. I'll take time to tackle it. And thanks for your approach on fix it.

@jenting When can we expect a fix for this issue?

**Comment by jenting** [comment]
I'll try my best this week _or_ next week.

**Comment by kashifest** [comment]
> I'll try my best this week _or_ next week.

Thank you. Do let me know if any help is needed.

**Comment by jenting** [comment]
> We tried adding a condition in the approver part and that seems to work. Perhaps this was not needed in older versions.

I did check from k8s 1.15 to k8s 1.22, all support authorization v1 version :tada: 
I'll apply your patch, thanks for your effort.
