### ISSUE TITLE
PodSecurity Policies are deprecated since 1.21 and will be removed in 1.25

### ISSUE THREAD

**Issue by kashifest** [jenting/kucero#33]
https://kubernetes.io/docs/concepts/policy/pod-security-policy/ 

Since KUCERO uses podsecurity policies perhaps its better to think about alternatives now.

**Comment by kashifest** [comment]
Have you given any thoughts on this @jenting ?

**Comment by jenting** [comment]
No, I haven't looked at the replacement of PSP. Do you have some idea/thought on this one?

**Comment by kashifest** [comment]
@jenting perhaps https://kubernetes.io/docs/concepts/security/pod-security-admission/ ?
